config/routes.rb
Carpool1::Application.routes.draw do

resources :parents, :students, :sessions

resources :activities do 
  resources :carpoolers
end
root 'landings#index'

get "show_student" => 'students#show_student', :as => :show_student

get "landings/new"

  

end

app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :parent
  belongs_to :activity

  email_regex = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i
  validates :first_name,	:presence		=> true,
  							:length			=> { :maximum => 75 }
  validates :last_name,		:presence		=> true,
  							:length			=> { :maximum => 75 }
  validates :email,			:presence	    => true,
  							:format 		=> { :with => email_regex, message: "Incorrect email format."},
           					:uniqueness 	=> { :case_sensitive => false }
  validates :gender,		:presence		=> true,
  							:length			=> { :maximum => 1}
  validates :birth_date,		:presence		=> true
  validates :home_school_name,	:presence	=> true,
  							:length			=> { :maximum => 75 }
  validates :school_phone_number ,	:presence		=> true
  before_save { self.email = email.downcase }

  def student_full_name
    [first_name,last_name].join(' ')
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def index
    @students = Student.all
  end

  def show
    @student = Student.find(params[:id])
  end

  def new
    @student = Student.new
    @student.gender = 'M'
  end

  def create
  @student = Student.new(student_params)

    if @student.save
      redirect_to students_path, :flash => { :notice => 'Student successfully saved.'}
    else
      redirect_to :back, :flash => { :state => 'register', :errors => @student.errors.full_messages } 
    end

  end

  def edit
    puts params
    @student = Student.find(params[:id])
  end

  def update
    puts params
    @student = Student.update(params[:id], student_params)
    redirect_to students_path
  end

  def destroy
    Student.find(params[:id]).destroy
    redirect_to students_path
  end
  
  private 
  def student_params
  params.require(:student).permit(:first_name, :last_name,:email,
  :gender,:birth_date,:home_school_name, :school_address_street,
  :school_address_city,:school_address_zipcode,:school_address_state,:school_phone_number,:parent_id)   
end

end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
 <script type="text/javascript">
      $('#datetimepicker').datetimepicker({
        format: 'dd/MM/yyyy hh:mm:ss',
        language: 'pt-BR'
      });
 </script>
<!-- <p>Find me in app/views/students/new.html.erb</p> -->

<div id='form-wrapper'>
	<% if flash[:errors] %>
		<% flash[:errors].each do |error| %>
			<p class='text-error'><%= error %></p>
		<% end %>
	<% end %>

	<h3>Student Information</h3>
	<%= simple_form_for @student, :html => {:class => 'well form-horizontal'} do |f| %>
	<div class="row-fluid">
	  <div class="span4 input-large">
		  <%= f.input :first_name, label: 'First Name', :html => {:class => 'input-small'} %>
		  <%= f.input :last_name, label: 'Last Name' %>
		  <%= f.input :email, label: 'Email' %>

		  <%= f.label :Gender, 'Gender'%>
		  <label class="radio inline">
			  <%= f.radio_button :gender, 'M'%>
			  <%= f.label :gender, 'Male', :value => 'Male' %>
		  </label>
		  <label class="radio inline">
			  <%= f.radio_button :gender, 'F', :checked => 'F' %>
			  <%= f.label :gender, 'Female', :value => 'Female' %>
		 </label>

		  <%= f.label :birth_date, 'Student Birthdate'%>
		  <div class="us_date">
  			<%= f.date_select :birth_date, {:start_year => Time.now.year - 14, :end_year => 1970, :prompt => true, :order => [:month, :day, :year]} %>
		  </div>
	   </div>

	  <div class="span4 input-large">
		  <%= f.input :home_school_name, label: 'Student Home School Name' %>
		  <%= f.input :school_address_street, label: 'School Street Address' %>
		  <%= f.input :school_address_city, label: 'School City Address' %>
		  <%= f.input :school_address_zipcode, label: 'School Zip Code' %>
		  <%= f.select :school_address_state, us_states %> 
		  <%= f.input :school_phone_number, label: 'School Phone' %>

		  <%= f.button :submit, :input_html => { :value => "\nSave"}, class: 'btn btn-primary'%>
	</div>

	<% end %>
	</div>

</div>

app/views/students/edit.html.erb
<div id="student_edit_modal" class="reveal-modal">
<!-- <h1>Students#edit</h1> -->

	<div id='form-wrapper'>
		<% if flash[:errors] %>
			<% flash[:errors].each do |error| %>
				<p class='text-error'><%= error %></p>
			<% end %>
	    <% end %>
	</div>

	<h3>Edit Student Information</h3>
	<%= simple_form_for @student, :html => {:class => ' well form-horizontal'} do |f| %>
	<div class="row-fluid">
	  <div class="span4 input-large">
		  <%= f.input :first_name, label: 'First Name', :html => {:class => 'input-small'} %>
		  <%= f.input :last_name, label: 'Last Name' %>
		  <%= f.input :email, label: 'Email' %>
		
		  <%= f.label :Gender, 'Gender' %>
		  <%=(@student.gender == "M" ? "Male" : "Female") %>
		</br>

		  <label class="radio inline">
			  <%= f.radio_button :gender, 'M'%>
			  <%= f.label :gender, 'Male', :value => 'Male' %>
		  </label>

		  <label class="radio inline">
			  <%= f.radio_button :gender, 'F', :checked => 'F' %>
			  <%= f.label :gender, 'Female', :value => 'Female' %>
		 </label>

		  <div class="us_date">
		  <%= f.input :birth_date, label: 'Student Birthdate' %>
		</div>
	 </div>
	  <div class="span4 input-large">
		  <%= f.input :home_school_name, label: 'Student Home School Name' %>
		  <%= f.input :school_address_street, label: 'School Street Address' %>
		  <%= f.input :school_address_city, label: 'School City Address' %>
		  <%= f.input :school_address_zipcode, label: 'School Zip Code' %>
		  <%= f.label :school_address_state, 'State' %>
		  <%= f.select :school_address_state, us_states, label: 'State'%> 
		  <%= f.input :school_phone_number, label: 'School Phone' %>

		  <%= f.button :submit, :input_html => { :value => "\nSave"}, class: 'btn'%>
	</div>

	<% end %>
	</div>
<!-- old edit below -->
<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>
</div>

app/views/students/edit2.html.erb
<h1>Students#edit</h1>
<!-- <p>Find me in app/views/students/edit.html.erb</p> -->

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<!-- <p>Find me in app/views/students/index.html.erb</p> -->

<h3 class="pull-left">List of all Students</h3>
</br>
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email address</th>
      <th>Gender</th>
      <th>Home School Name</th>
      <th>School Zipcode</th>
      <th>School Phone Number</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.first_name %></td>
        <td><%= student.last_name %></td>
        <td><%= student.email %></td>
		    <td><%= student.gender == "M" ? "Male" : "Female"%></td>
        <td><%= student.home_school_name %></td>
        <td><%= student.school_address_zipcode %></td>
        <td><%= student.school_phone_number %></td>
        <td><%= link_to 'Show', student_path(student.id) %></td>
        <td>
          <a href="<%= edit_student_path(student.id) %>" data-reveal-id="student_edit_modal" class="btn btn-mini">Edit</a>
        </td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>

<%= link_to 'To add a new Student click here', new_student_path, :class => "pull-right" %>
  <!-- <div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>
</table>

<br>
<div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div> -->

app/views/students/new.html.erb
<%= link_to 'Back', students_path %>
<%= render 'form' %>

app/views/students/show.html.erb
    <h3>Student Information</h3>
<!-- <h1>Students#show</h1>
<p>Find me in app/views/students/show.html.erb</p> -->

<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @student.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @student.last_name %>
</p>

<p>
  <strong>Gender:</strong>
  <%= (@student.gender == "M" ? "Male" : "Female")%>
</p>

<p>
  <strong>Email address:</strong>
  <%= @student.email%>
</p>

<p>
  <strong>Home School Name :</strong>
  <%= @student.home_school_name%>
</p>

<p>
  <strong> School Address Street :</strong>
  <%= @student.school_address_street%>
</p>

<p>
  <strong> School - City:</strong>
  <%= @student.school_address_city%>
</p>

<p>
  <strong> School Zipcode:</strong>
  <%= @student.school_address_zipcode%>
</p>

<p>
  <strong> School - State:</strong>
  <%= state_name(@student.school_address_state)%>
</p>

<p>
  <strong> School Phone Number :</strong>
  <%= @student.school_phone_number%>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>