config/routes.rb
Carpool1::Application.routes.draw do

resources :parents, :students, :sessions

resources :activities do 
  resources :carpoolers
end
root 'landings#index'

get "show_student" => 'students#show_student', :as => :show_student

get "landings/new"

  

end

app/models/parent.rb
class Parent < ActiveRecord::Base
  has_many :students
  has_many :carpoolers

  email_regex = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i

  validates :first_name,	:presence		=> true,
  							:length			=> { :maximum => 75 }
  validates :last_name,		:presence		=> true,
  							:length			=> { :maximum => 75 }
  validates :email,			:presence	    => true,
  							 :format 		=> { :with => email_regex, message: "Incorrect email format."},
           					:uniqueness 	=> { :case_sensitive => false, message: " address has already been taken, please enter a unique email"}
  validates :password,      :length			=> { :within => 6..40 }
  validates :address_street,:presence		=> true,
  							:length			=> { :maximum => 45 }
  validates :address_city,:presence			=> true,
  							:length			=> { :maximum => 45 }
  validates :address_state,:presence		=> true,
  							:length			=> { :maximum => 2 }
  validates :phone_home ,	:presence		=> true
  validates :phone_mobile ,:presence		=> true

  before_save { self.email = email.downcase }
  has_secure_password

  def parent_full_name
    [first_name,last_name].join(' ')
  end

end

app/controllers/parents_controller.rb
class ParentsController < ApplicationController
  def index
    @parents = Parent.all
  end

  def show
    @parent = Parent.find(params[:id])
  end

  def new
    @parent = Parent.new
  end

  def create
    @parent = Parent.new(parent_params)

    if @parent.save
      # sign_in @parent
      redirect_to parents_path
    else
      redirect_to :back, :flash => { :state => 'register', :errors => @parent.errors.full_messages } 
    end
  end

  def edit
    # puts params
    @parent = Parent.find(params[:id])
  end

  def update
    # puts params
    @parent = Parent.update(params[:id], parent_params)
    redirect_to parents_path
  end

  def destroy
    Parent.find(params[:id]).destroy
    redirect_to parents_path
  end

 private
  def parent_params
    params.require(:parent).permit(:first_name, :last_name, :email, :password,:password_confirmation,:address_street,:address_city,:address_zipcode,
    :address_state,:phone_home, :phone_mobile)
  end 
end

app/helpers/parents_helper.rb
module ParentsHelper

  def sign_in(parent)
    session[:parent_id] = parent.id
    self.current_parent = parent
  end
  
  # setter method
  def current_parent=(parent)
    @current_parent = parent
  end

  # getter method
  def current_parent
    @current_parent ||= parent.find(session[:parent_id]) if session[:parent_id]
  end

  def signed_in?
    !current_parent.nil?
  end

  def sign_out
    session[:parent_id] = nil
    self.current_parent = nil
  end

  def current_parent?(parent)
    parent == current_parent 
  end

  def deny_access
    redirect_to welcome_path, :notice => "Please sign in to access this page."
  end

end

app/views/parents/_form.html.erb
<!-- <p>Find me in app/views/parents/new.html.erb</p> -->

<div id='form-wrapper'>
	<% if flash[:errors] %>
		<% flash[:errors].each do |error| %>
			<p class='text-error'><%= error %></p>
		<% end %>
	<% end %>
</div>

	<h3>Parent Information</h3>
	<%= simple_form_for @parent, :html => {:class => 'well form-horizontal'} do |f| %>
	<div class="row-fluid">
		<div class="span4 input-large">
			  <%= f.input :first_name, label: 'First Name' %>
			</br>
			  <%= f.input :last_name, label: 'Last Name' %>
			</br>
			  <%= f.input :email, label: 'Email' %>
			</br>
			  <%= f.input :password, label: 'Password' %>
			</br>
			  <%= f.input :password_confirmation, label: 'Confirm Password' %>
			</br>
		</div>	

		<div class="span4 input-large pull-right">
		    <%= f.input :address_street, label: 'Street Address' %>
			</br>
			  <%= f.input :address_city, label: 'City Address' %>
			</br>
			  <%= f.label :address_state, 'Address State'%>
			  <%= f.select :address_state, us_states %> 
			</br>
			  <%= f.input :address_zipcode, label: 'Zip Code' %>
			</br>
			  <%= f.input :phone_home, label: 'Home Phone' %>
			</br>
			  <%= f.input :phone_mobile, label: 'Mobile Phone' %>
			</br>
			  <%= f.button :submit, value:'Save', class: 'btn btn-primary'%>
		</div>
	<% end %>
</div>

app/views/parents/edit.html.erb
<!-- <h1>Parents#edit</h1> -->
<!-- <p>Find me in app/views/parents/edit.html.erb</p> -->
<%= link_to 'Show', @parent%> |
<%= link_to 'Back', parents_path %>

<h3> Edit </h3><%= render 'form' %>

app/views/parents/index.html.erb
<!-- <h1>Parents#index</h1>
<p>Find me in app/views/parents/index.html.erb</p> -->
<h3 class="pull-left">List of all Parents</h3>

<%= link_to 'To add a new Parent click here', new_parent_path,:class => "pull-right" %>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email address</th>
      <th>Street Address </th>
      <th>City</th>
      <th>Zipcode</th>
      <th>State</th>
      <th>Phone Home</th>
      <th>Phone Mobile</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @parents.each do |parent| %>
      <tr>
        <td><%= parent.first_name %></td>
        <td><%= parent.last_name %></td>
        <td><%= parent.email %></td>
        <td><%= parent.address_street %></td>
        <td><%= parent.address_city %></td>
        <td><%= parent.address_zipcode %></td>
        <td><%= state_name(parent.address_state) %></td>
        <td><%= parent.phone_home%></td>
        <td><%= parent.phone_mobile%></td>
        <td><%= link_to 'Show', parent_path(parent.id) %></td>
        <td>
          <a href="<%= edit_parent_path(parent.id) %>" data-reveal-id="parent_edit_modal" class="btn btn-mini">Edit</a>
        </td>
        <td><%= link_to 'Delete', parent, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>

app/views/parents/new.html.erb
<!-- <h2>New Parent Registration</h2> -->
<!-- <p>Find me in app/views/activities/new.html.erb</p> -->
<%= link_to 'Back', parents_path %>
<%= render 'form' %>

app/views/parents/show.html.erb
<h1>Parents#show</h1>
<!-- <p>Find me in app/views/parents/show.html.erb</p> -->
<!-- <p>Find me in app/views/activities/show.html.erb</p> -->

<p id="notice"><%= notice %></p>

<div class="well">
	<p>
	  <strong>First Name of Parent:</strong>
	  <%= @parent.first_name %>
	</p>

	<p>
	  <strong>Last Name of Parent:</strong>
	  <%= @parent.last_name %>
	</p>

    <p>
    <strong>Parent email:</strong>
    <%= @parent.email %>
    </p>

<h2> Location of Parent - Address </h2>
	<p>
	  <strong> Street Address:</strong>
	  <%= @parent.address_street%>
	</p>

	<p>
	  <strong> City:</strong>
	  <%= @parent.address_city%>
	</p>

	<p>
	  <strong> Zipcode:</strong>
	  <%= @parent.address_zipcode%>
	</p>

	<p>
	  <strong> State:</strong>
	  <%= state_name(@parent.address_state)%>
	</p>

	<p>
	  <strong> Parent Home Phone Number :</strong>
	  <%= @parent.phone_home%>
	</p>

	<p>
	  <strong> Parent Mobile Phone Number :</strong>
	  <%= @parent.phone_mobile%>
	</p>

</div>
<%= link_to 'Edit', edit_parent_path(@parent) %> |
<%= link_to 'Back', parents_path %>

app/views/parents/update.html.erb
<h1>Parents#update</h1>
<p>Find me in app/views/parents/update.html.erb</p>