config/routes.rb
Carpool1::Application.routes.draw do

resources :parents, :students, :sessions

resources :activities do 
  resources :carpoolers
end
root 'landings#index'

get "show_student" => 'students#show_student', :as => :show_student

get "landings/new"

  

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  validates :activity_name,:activity_start_date, :activity_start_time, :presence => true
  validates :activity_end_time, :address_street, :address_city, :presence => true
  validates :address_state,:presence		=> true,
  							:length			=> { :maximum => 2 }
  has_many :students
  has_many :parents
  has_many :carpoolers
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController

  def index
    @activities = Activity.all
  end

  def show
    @activity = Activity.find(params[:id])
  end

  def new
    @activity = Activity.new
  end

  def create
    @activity = Activity.new(activity_params)

    if @activity.save
      redirect_to activities_path
    else
      redirect_to :back, :flash => {:state => 'register', :errors => @activity.errors.full_messages } 
    end
  end

  def edit
    @activity = Activity.find(params[:id])
  end

  def update
    puts params
    @activity = Activity.update(params[:id], activity_params)
    redirect_to activities_path
  end

  def destroy
    Activity.find(params[:id]).destroy
    redirect_to activities_path
  end
  
  private 

  def activity_params
    params.require(:activity).permit(:activity_name, :activity_start_date,:activity_end_date,
    :activity_start_time,:activity_end_time,:address_street,:address_city,:address_zipcode,
    :address_state,:phone_number)   
  end

end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_form.html.erb
<script>
      $('.datepicker').datepicker({
          format: "yyyy-mm-dd",
          todayHighlight: true,
          todayBtn: 'linked',
          autoclose: true
      }); ;
</script>

<div id='form-wrapper'>
	<% if flash[:errors] %>
		<% flash[:errors].each do |error| %>
			<p class='text-error'><%= error %></p>
		<% end %>
	<% end %>
</div>

<h3>Activity Information</h3>

<%= simple_form_for @activity, :html => {:class => 'well form-horizontal'} do |f| %>
<div class="row-fluid">
	<div class="span4 input-large">
		  <%= f.input :activity_name, label: 'Activity Name', :html => {:class => 'input-small'} %>
		</br>
		  <%= f.label :activity_start_date, 'Activity Start Date'%>
		  <div class="us_date">
  			<%= f.date_select :activity_start_date, label: 'Activity Start Date' %>
  		  </div>
  		  </br>
		  <%= f.label :activity_end_date, 'Activity End Date'%>
		  <div class="us_date">
		  	<%= f.date_select :activity_end_date, label: 'Activity End Date' %>
		  </div>
		</br>
		<div class="us_time">
			<%= f.label :activity_start_time, 'Activity Start Time'%>
			<%= f.time_select("activity_start_time", prompt:{hour: 'Hour', minute: 'Minute'},ampm: true) %>
		</div>

		</br>
		<div class="us_time">
			<%= f.label :activity_end_time, 'Activity End Time'%>
			<%= f.time_select("activity_end_time", prompt: {hour: 'Hour', minute: 'Minute'}, ampm: true ) %>
		</div>
	 </div>

	 <div class="span4 input-large">
		  <%= f.input :address_street, label: 'Activity Street Address' %>
			</br>
		  <%= f.input :address_city, label: 'Activity City Address' %>
		  </br>
		  <%= f.input :address_zipcode, label: 'Activity Zip Code' %>
		  </br>

		  <%= f.label :address_state, 'Address State'%>
		  <%= f.select :address_state, us_states %> 
		  </br>
		  </br>
		  <%= f.input :phone_number, label: 'Activity Contact Phone' %>
		  </br>
		  <%= f.button :submit, value:'Save', class: 'btn btn-primary'%>
	</div>
<% end %>
</div>

app/views/activities/edit.html.erb
<!-- <h1>Activities#edit</h1> -->
<!-- <p>Find me in app/views/activities/edit.html.erb</p> -->
<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>
<h3> Edit </h3><%= render 'form' %>

app/views/activities/index.html.erb
<!-- <h1>Activities#index</h1> -->
<!-- <p>Find me in app/views/activities/index.html.erb</p> -->
<h3 class="pull-left">List all activities</h3>
<%= link_to 'Add a new Activity here', new_activity_path, :class => "pull-right" %>
<table class='table table-striped table-bordered'>
  <thead>
    <tr>
      <th>Name</th>
      <th>Start Date</th>
      <th>End Date</th>
      <th>Start Time</th>
      <th>End Time</th>
      <th>Activity Address:Street</th>
      <th>City </th>
      <th>Zipcode</th>
      <th>State</th>
      <th>Contact Phone Number</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>


  <tbody>
    <% @activities.each do |activity| %>
      <tr>
        <td><%= activity.activity_name %></td>
        <td><%= activity.activity_start_date.strftime("%B-%d-%Y")%></td>
        <td><%= activity.activity_end_date.strftime("%B-%d-%Y")%></td>
        <td><%= activity.activity_start_time.strftime("%I:%M %p")%></td>
        <td><%= activity.activity_end_time.strftime("%I:%M %p")%></td>
        <td><%= activity.address_street %></td>
        <td><%= activity.address_city %></td>
        <td><%= activity.address_zipcode %></td>
        <td><%= state_name(activity.address_state) %></td>
        <td><%= activity.phone_number %></td>
        <td><%= link_to 'Show', activity %></td>
        <td><%= link_to 'Edit', edit_activity_path(activity) %></td>
        <td><%= link_to 'Destroy', activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/activities/new.html.erb
<!-- <h1>Activities#new</h1> -->
<!-- <p>Find me in app/views/activities/new.html.erb</p> -->
<%= link_to 'Back', activities_path %>
<%= render 'form' %>

app/views/activities/show.html.erb
<h3>View Activity Information</h3>
<!-- <p>Find me in app/views/activities/show.html.erb</p> -->
<p id="notice"><%= notice %></p>
</br>

<p>
  <strong>Name of Activity:</strong>
  <%= @activity.activity_name %>
</p>

<div class="row-fluid">
  <div class="span4">
    <p>
    <strong>Activity Start Date:</strong>
    <%= @activity.activity_start_date.strftime("%B-%d-%Y") %>
    </p>
  </div>

    <div class="span4">
      <p class="pull-right">
        <strong>Activity End Date:</strong>
        <%= @activity.activity_end_date.strftime("%B-%d-%Y") %>
      </p>
    </div>
</div>

<div class="row-fluid">
  <div class="span4">
    <p>
      <strong>Activity Start time:</strong>
      <%= @activity.activity_start_time.strftime("%I:%M %p") %>
    </p>
  </div>

  <div class="span4">
    <p class="pull-right">
      <strong>Activity End time:</strong>
      <%= @activity.activity_end_time.strftime("%I:%M %p") %>
    </p>
  </div>
</div>

</br>
<h3> Location of Activity - Address </h3>
</br>
<p>
  <strong> Street Address:</strong>
  <%= @activity.address_street%>
</p>
<div class="clear"></div>

<p>
  <strong> City:</strong>
  <%= @activity.address_city%>
</p>

<p>
  <strong> Zipcode:</strong>
  <%= @activity.address_zipcode%>
</p>

<p>
  <strong> State:</strong>
  <%= state_name(@activity.address_state)%>
</p>

<p>
  <strong> Activity Contact Phone Number :</strong>
  <%= @activity.phone_number%>
</p>

<%= link_to 'Edit', edit_activity_path(@activity) %> |
<%= link_to 'Back', activities_path %>